version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/licsensei
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  disable: true

checksum:
  name_template: "checksums.txt"
