name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Tests
        run: make test

      - name: License check
        run: make license-check

      - name: License header check
        run: make license-header-check
